# Generated by Django 3.2 on 2025-08-10 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PRORROGADA', 'Prorrogada')], max_length=10)),
                ('atividade', models.CharField(choices=[('ATV1', 'ATV1'), ('ATV2', 'ATV2'), ('ATV3', 'ATV3'), ('ATV4', 'ATV4'), ('ATV5', 'ATV5')], default='ATV1', max_length=4, verbose_name='Atividade Complementar')),
                ('dt_inicio', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Inicio')),
                ('dt_fim', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Fim')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplina_atividades', to='courses.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professor_atividades', to='accounts.professor')),
                ('turma', models.ManyToManyField(blank=True, related_name='turma_atividades', to='courses.Turma')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ENT', 'Entregue'), ('COR', 'Corrigido'), ('PEN', 'Pendente')], default='PEN', max_length=3)),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dt_entrega', models.DateField(auto_now=True)),
                ('observacao', models.TextField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividade_entregue', to='activities.atividade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.professor')),
            ],
            options={
                'verbose_name_plural': 'Entrega da Atividade',
            },
        ),
    ]
