# Generated by Django 3.2 on 2024-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_professor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='professor',
            name='rp',
            field=models.CharField(blank=True, max_length=10, verbose_name='RP'),
        ),
    ]
