# Generated by Django 3.2 on 2024-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_professor_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ManyToManyField(related_name='turma', to='app.Disciplina'),
        ),
    ]
