# Generated by Django 3.2 on 2024-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_turma_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_lecionadas', to='app.Disciplina'),
        ),
    ]
