# Generated by Django 3.2 on 2024-10-01 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_professor_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_turmas', to='app.curso'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ManyToManyField(related_name='disciplinas_turma', to='app.Disciplina'),
        ),
    ]
