# Generated by Django 3.2 on 2024-10-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_auto_20241001_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplina_atividades', to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professor_atividades', to='app.professor'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='turma',
            field=models.ManyToManyField(blank=True, related_name='turma_atividades', to='app.Turma'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador_cursos', to='app.coordenador'),
        ),
        migrations.AlterField(
            model_name='entregaatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividade_entregue', to='app.atividade'),
        ),
    ]
