# Generated by Django 3.2 on 2025-08-10 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=10, unique=True, verbose_name='RA')),
                ('data_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.CharField(blank=True, max_length=10, unique=True, verbose_name='RP')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem')),
            ],
        ),
    ]
