# Generated by Django 3.2 on 2025-08-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(default=None, max_length=500, verbose_name='Descricao')),
                ('periodo', models.CharField(choices=[('Matutino', 'Matutino'), ('Noturno', 'Noturno')], default='MATUTINO', max_length=20)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('ONLINE', 'ONLINE')], default='PRESENCIAL', max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador_cursos', to='accounts.coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horaria')),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/')),
                ('curso', models.ManyToManyField(to='courses.Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('TURMA A', 'TURMA A'), ('TURMA B', 'TURMA B'), ('TURMA C', 'TURMA C'), ('TURMA D', 'TURMA D')], default=None, max_length=7, verbose_name='Turma')),
                ('semestre', models.CharField(choices=[('1° SEMESTRE', 'PRIMEIRO SEMESTRE'), ('2° SEMESTRE', 'SEGUNDO SEMESTRE'), ('3° SEMESTRE', 'TERCEIRO SEMESTRE'), ('4° SEMESTRE', 'QUARTO SEMESTRE')], default='1° SEMESTRE', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_turmas', to='courses.curso')),
                ('disciplina', models.ManyToManyField(related_name='disciplinas_turma', to='courses.Disciplina')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATV', 'Ativa'), ('Canc', 'Cancelada'), ('Trc', 'Trancada'), ('An', 'Em Analise'), ('SO', 'Solicitada')], default=None, max_length=4)),
                ('dt_inicio', models.DateField()),
                ('dt_final', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluno_matricula', to='accounts.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso_matricula', to='courses.curso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turma_matricula', to='courses.turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('turma', 'curso', 'semestre'), name='unique_turma'),
        ),
    ]
